### ISSUE TITLE
Nightscout Pill doesn't reflect Red Loop

### ISSUE THREAD

**Issue by marionbarker** [nightscout/Trio#137]
This is with alpha branch.

I believe the OpenAPS pill should indicate last time loop enacted and go yellow at 30 minutes since last time it successfully enacted. (That's what happens with iAPS implementation).

The OpenAPS pill (with alpha) shows the last time any upload happened including Not Enacted.

See thread in discord:
* https://discord.com/channels/1020905149037813862/1233516166584995890

**Comment by marionbarker** [comment]
Bump - this needs to be checked but if it is still true, I would think parents would be very concerned.

**Comment by dnzxy** [comment]
This is due to Trio – based on the explicit wishes of caregivers and devs on the team that are caregivers – uploads both suggested and enacted determinations, thus keeping the OpenAPS pill relatively up to date, even in case of not looping events. iAPS does not do that. Closing, since this would go specifically against a change done by the Trio team.
