### ISSUE TITLE
Add spacing for exceeding max bolus warning

### ISSUE THREAD

**Issue by JeremyStorring** [nightscout/Trio#210]
**Describe the bug**
When the user exceeds their max bolus, the formatting of the error is a bit ugly.

**To Reproduce**
1. Go to bolus
2. Enter amount > max bolus
3. See warning "Max bolus exceeded! (>#U)"

**Expected behavior**
I believe that the warning should
1) Be more visible, instead of blending in with everything else
2) Have different wording, such as "Max bolus of # U exceeded."

**Screenshots**
![image](https://github.com/nightscout/Trio/assets/37644909/cc814be9-2359-4a9b-8707-3c5e5e94d858)

**Smartphone (please complete the following information):**
iPhone 14 (but not applicable)

**Setup Information (please complete the following information):**
* Pump type: Omnipod Dash
* CGM type and CGM app: Dexcom G7 + G7 App
* Trio version, branch and git reference (see Trio Settings): Dev 0.1.0

**Comment by bjornoleh** [comment]
I agree with the suggestions above. The current grey colour is not very noticeable. The rewording could make it a little clearer too.

**Comment by MikePlante1** [comment]
I agree a color change here would be helpful. How about just changing the text color to red?
After [line 92](https://github.com/nightscout/Trio/blob/5e5134413db43eb1dc5f08e700c966507fc28b0f/FreeAPS/Sources/Modules/Bolus/View/BolusRootView.swift#L92) in BolusRootView:
```swift
.foregroundStyle(state.amount <= 0 ? .gray : state.amount > state.maxBolus ? .red : .blue)
```
<img width="350" alt="Screenshot 2024-05-19 at 10 34 24 AM" src="https://github.com/nightscout/Trio/assets/82073483/632be5a8-56ed-42a3-8925-68f14e98cd92">

***

I used this wording in #172 because I didn't want to break the translations that already exist for this label, and inserting a variable in the middle of the label splits it into two separate translations.

old: `Max Bolus exceeded!` + `U`
your suggestion: `Max Bolus of` + `U exceeded`
or to retain the current units translations: `Max Bolus of` + `U` + `exceeded`

**Comment by JeremyStorring** [comment]
@MikePlante1 this all looks good to me. I agree with making the text red, and we can use `Max Bolus of` + `U` + `exceeded` to retain translations :)

**Comment by MikePlante1** [comment]
That’s the thing, though… changing it means translations aren’t retained. It is a better wording, and there are already plenty of changes that need to be retranslated, so I’ll put this together for a PR. Maybe I’ll combine it with adding a similar feature for Max Carbs.

**Comment by MikePlante1** [comment]
Potential solution added in #226
