### ISSUE TITLE
(Feature request) Option to log basal portion of SMB as basal rather than bolus

### ISSUE THREAD

**Issue by LiroyvH** [nightscout/Trio#246]
I'd prefer it if the basal portion of an SMB (when applicable) is logged as basal (rather than as a bolus) to both Nightscout as well as Apple Health. Currently it's all logged as bolus insulin, which makes it rather hard to read exactly how much basal was actually administered; making statistics and fine-tuning based on the data very hard to accomplish.

I'm not sure if there's an underlying reason why this wouldn't be possible; but this would be nice.

**Comment by Sjoerd-Bo3** [comment]
Are you okay in formatting like this? Per feature request template:

## Is your feature request related to a problem? Please describe.
*Currently, the basal portion of a Super Micro Bolus (SMB) is logged as a bolus rather than as basal insulin in both Nightscout and Apple Health. This makes it difficult to accurately track how much basal insulin has been administered, complicating statistics and fine-tuning based on the data.*

## Describe the solution you'd like
*Add an option to log the basal portion of an SMB as basal insulin instead of bolus insulin. This change should be reflected in both Nightscout and Apple Health.*

## Describe alternatives you've considered
*1. Manually adjusting the logs to separate basal and bolus insulin, which is time-consuming and prone to errors.*
*2. Continuing with the current system, which limits the accuracy of insulin tracking and data analysis.*

## Additional context
*Accurate logging of insulin types is crucial for effective diabetes management, enabling better analysis and adjustments. By correctly categorizing the basal portion of SMBs, users can gain clearer insights into their insulin usage and make more informed decisions.*

## Technical Details
*This feature requires changes to how SMBs are logged in the Trio app, ensuring the basal portion is categorized correctly in both Nightscout and Apple Health.*

## User Impact
*Medium – This feature will improve data accuracy for users, enhancing their ability to manage and adjust their insulin therapy effectively.*

## Priority Level
*Low – While beneficial for data accuracy, this feature is not critical to the core functionality of the app.*

**Comment by bjornoleh** [comment]
I agree that the current split between basal and bolus is of little value when an APS is involved, especially when using SMB (but also in Loop with AB). 

For now, you can solve this in two ways. 

1. Look up the sum of programmed basals in Trio, and compare this with the TDD

2. Use the summary at the bottom of the Day today report in NS. The “Base basal average” value is programmed basal as percentage of TDD. 

It might look something like this:

TDD average: 24.0U  Bolus average: 79%  Basal average: 21%  (Base basal average: 40%)  Carbs average: 181gProtein average: 0gFat average: 0g


![image](https://github.com/nightscout/Trio/assets/63544115/206e3367-1428-408f-bc16-e2115eefcaf9)

This metric in absolute value (units) is also displayed for each day on the right hand side:

![image](https://github.com/nightscout/Trio/assets/63544115/cce3671a-f822-499d-a89e-d7a29d83a53b)

**Comment by aug0211** [comment]
I typically just look at my programmed total basal rate (which happens to end up right around 50%, what do ya know). The actual delivered stats tend to be anywhere from 90% bolus/10% basal to 80% bolus/20% basal though.

This would be really cool and a clear improvement, I think, over trying to deduce an approximation based on other data points.

**Comment by dsut4392** [comment]
What information do you gain by comparing basal vs bolus percentage? In my mind, the distinction is arbitrary, whether or not you are using an APS, or even a pump. In a basal testing scenario, all that's really important is whether your programmed basal was too little/about right/too much to keep you in range - the Loopalyzer report in Nightscout is really good for this, as it shows net IOB vs BG, and it doesn't matter whether the net IOB is a result of "temp basal" or "SMB".

**Comment by Sjoerd-Bo3** [comment]
hey 👋 - silence for 30 days 🤐 ... anybody? triage is required!

**Comment by dnzxy** [comment]
This would come with a change of oref, as oref does the dosing decision, and frankly we will not be changing oref. Dosing in Trio happens based on the determination result and if it deems a microbolus is required. The required dose will then be bolused for. I'm inclined to close this, sorry.

**Comment by LiroyvH** [comment]
@dnzxy I don't think that it requires changes to oref, but to how the app logs in Apple Health and Nightscout; unless oref doesn't give any hint as to how it came to the SMB calculation?

**Comment by dnzxy** [comment]
It requires changes to oref because you need to change specific information you get from oref at specific points during the calculation. Oref will only respond with insulin required and a micro bolus and/or TB dose. That/these dose/s is/are enacted and upon enacting them they are stored in Apple Health. There is no such thing as knowing the basal portion of a given micro bolus from what information we get. The basal bolus concept is also pretty irrelevant if I‘m being frank, it’s insulin at the end of the day.

**Comment by LiroyvH** [comment]
@dnzxy: alright, if it can't be done it can't be done. C'est la vie. :) 

It's true btw that insulin is insulin, but imho that statement only really works when you keep using SMB's or this kind of solution in general. You get inaccurate data fed to your databases, which not only screws with the reports but also for profile analysis. Eg: if I want to query my Nightscout right now to determine what to feed to my calculations to switch to pen therapy (rather than an educated guess based on what would otherwise be programmed), its skewed data that cannot properly reveal what basal was actually administered over a period of time as it believes the majority is all bolus. Hence why if the SMB contains a basal portion: it'd be nice to know what that was _and_ what it withholds if it sees a drop (which is even harder to see). 

I love (properly labeled) data. But if we don't have the data, we don't have the data - simple as that. :P
