### ISSUE TITLE
NS uploads are intermittent.

### ISSUE THREAD

**Issue by JohnKitching** [nightscout/Trio#256]
I believe this is an old issue going back several iterations of FAX, iAPS etc but now seems to be in Trio too. 

Uploads of data for the openAPS pill and predictions are intermittent. 

I'm not sure it's relevant but I'm on TAI with Dash and Libre 2 and using Google to host NS.

**Comment by JohnKitching** [comment]
Including COB here is probably unfair. Trio does upload carbs but they often (always?) don't show in the COB pill. That could be (probably is?) an NS function.

**Comment by bjornoleh** [comment]
> Including COB here is probably unfair. Trio does upload carbs but they often (always?) don't show in the COB pill. That could be (probably is?) an NS function.

COB pill history not showing is a NS issue, and there is an open PR for that if I remember correctly.

**Comment by JohnKitching** [comment]
> > Including COB here is probably unfair. Trio does upload carbs but they often (always?) don't show in the COB pill. That could be (probably is?) an NS function.
> 
> 
> 
> COB pill history not showing is a NS issue, and there is an open PR for that if I remember correctly.

You're right. I've edited the issue. I think the predictions and openAPS pill issue is valid though.

**Comment by Sjoerd-Bo3** [comment]
hey 👋 - no triage is done for 30 days 🤐 ... anybody? triage is required!

**Comment by dnzxy** [comment]
Hi @JohnKitching 
not entirely sure what intermittent means in this context. If you mean the pill is populated and then it's not, it can be because the default configuration of NS uploads for the NSDeviceState (what feeds the OpenAPS pill) is only built so that it uploads enacted oref determination data. This means whenever you run into a yellow loop situation, and that can happen quite often, e.g. bolusing a larger dose at the end of the cycle will prevent the next determination from being enacted, you will not see this data uploaded to NS. 

This has since been updated, see https://github.com/nightscout/Trio/blob/dev/FreeAPS/Sources/Services/Network/NightscoutManager.swift#L319-L326 (notice that it uploads both suggested and enacted here). It was updated March 17. Your ticket dates to June 1st. TAI dev which you are running has that same change, see https://github.com/mountrcg/Trio/blob/dev-Tai/FreeAPS/Sources/Services/Network/NightscoutManager.swift

Be that as it may, the NS layer is more or less rewritten, as will be the persistence layer that feeds the app - all leading to better performance, also for uploading to NS. This is a post initial release thing, so not that much talk about it.

**Comment by dnzxy** [comment]
Addressed in TCD / Trio 1.0.0-dev.
