### ISSUE TITLE
Modify autotune to work with dynamic settings

### ISSUE THREAD

**Issue by JohnKitching** [nightscout/Trio#258]

**Comment by dnzxy** [comment]
Dear John, 

please follow our issue template (I'll paste it below) and update your feature request. Your issue is pretty open for interpretation and I'm sure you have quite specific outcomes in mind of what this feature should entail and how it should be implemented (from a user perspective, not from a technical one.)

Thanks.

<details><summary>Enhancement Issue Template</summary>
<p>

## Is your feature request related to a problem? Please describe.
*Provide a clear and concise description of the problem. Explain how this issue affects your experience with the Trio app and any specific scenarios where it occurs.*

## Describe the solution you'd like
*Detail the desired change or feature you'd like to see implemented in the Trio app. Be specific about how this solution would improve your experience and address the problem described above.*

## Describe alternatives you've considered
*List and describe any alternative solutions or features you've considered that could also address the problem. Explain why you believe the proposed solution is the best option.*

## Additional context
*Include any other context, screenshots, or relevant information that might help in understanding the issue or the proposed solution. If applicable, describe any previous discussions or decisions that relate to this feature request.*

## Technical Details
*If applicable, provide any technical details or considerations that might impact the implementation of this feature. This could include dependencies, potential risks, or required changes to existing functionalities.*

## User Impact
*(Optional) Describe the impact of this issue on your use of the Trio app. Include any specific examples or data that demonstrate how widespread or severe the problem is.*


</p>
</details>

**Comment by JohnKitching** [comment]
The Autotune algorithm is designed to work with a single ISF for the whole period it's analysing. 
This causes it not to work well with anything that results in multiple ISFs and / or CRs throughout the analysis period. This may be scheduled changes, dynamic ISF, autoISF, profile changes etc. 
This request is to modify the algorithm to handle these ISF / CR changes over the analysis period. 
The algorithm looks relatively easy to modify if the historical ISFs and CRs are known. 
I'm not sure how to say this other than make it work so I'm not sure what to put in the template. Sorry.

**Comment by Sjoerd-Bo3** [comment]
hey 👋 - no triage is done for 30 days 🤐 ... anybody? triage is required!

**Comment by dnzxy** [comment]
The Trio team has decided to remove Autotune from the app until a good solution for using AT is found.

There are existing problems (AT suggests 0u/hr basal rates) or AT in its current implementation is not compatible with modern use in AIDs (requirement of static CR and ISF, etc.).

Will be revisited, when time permits. Possibly during NFHack 2024.
