### ISSUE TITLE
Implement Accu Check Combo as a pump

### ISSUE THREAD

**Issue by SSSerafin** [nightscout/Trio#401]
Hello, would it be possible to create in near future version which will slow to Connect iPhone and accu check combo, to let me have only one phone instead of two?

**Comment by Sjoerd-Bo3** [comment]
> Hello, would it be possible to create in near future version which will slow to Connect iPhone and accu check combo, to let me have only one phone instead of two?

Near future is? Developing a driver for a pomp will take several months to a year minimum. After someone decides to do it. It’s an old pump. There is no iOS implementation yet and therefore very unlikely. Better to try AAPS if you want to keep that pump. Or switch to a modern pump😊

Hope this helps!

**Comment by LiroyvH** [comment]
The last model sold of this one will EOL at the latest next year. Will they continue making infusion sites for it? (You see if not, then by the time the driver would be done it might not even be usable anymore heh.) If you want to quickly swap you may want to look to obtain an old Medtronic 7xx. They're compatible and their infusion sets are the same as Medtronic's current line-up so will be available for years to come.

**Comment by MikePlante1** [comment]
> Is it possible also to work with 670G? or 740 would work as well?

 No. Only the following:

Medtronic 515 or 715 (any firmware)
Medtronic 522 or 722 (any firmware)
Medtronic 523 or 723 (firmware 2.4 or lower)
Medtronic Worldwide Veo 554 or 754 (firmware 2.6A or lower)
Medtronic Canadian/Australian Veo 554 or 754 (firmware 2.7A or lower)

> If you want to quickly swap you may want to look to obtain an old Medtronic 7xx + *Link. They're compatible and their infusion sets are the same as Medtronic's current line-up so will be available for years to come.

Note that you can still use the 5xx series with the current 3.0 mL reservoirs, you just have to cut them first which is a bit of a hassle. I hear [this tool](https://www.thingiverse.com/thing:3668313) makes thY easier, though:

**Comment by dnzxy** [comment]
1. Please use the feature request template that is prompted when you open an enhancement issue.
2. Roche pumps are a dying breed, as has been mentioned by previous comments. An iOS driver for Roche pumps is currently not in the works. I personally don't think looking at that deems resources well spent.
3. If you can contribute, know iOS developers that want to contribute and have the resources (time, test devices, etc.) to port existing Android APS drivers (Kotlin-based) to Swift for this, you're more than welcome and the Trio team will try to provide you the support you need. Otherwise, this is not really planned, nor on the roadmap.
