### ISSUE TITLE
Enhanced Insulin Flexibility: Introducing U-100 and U-200 Concentration Options in Trio

### ISSUE THREAD

**Issue by WEBSALJR** [nightscout/Trio#440]
To improve Trio’s flexibility and personalization, we could introduce an option allowing users to select their insulin concentration—either U-100 or U-200 insulin. This feature would provide the following benefits:
	1.	Personalized Dosing Precision: Users who need higher or lower concentrations for various lifestyle needs or insulin resistance can set their concentration type. Once chosen, Trio could automatically adjust the bolus and basal doses, preventing dosing errors and ensuring accurate insulin delivery.
	2.	Reduced Manual Calculations: By automating the adjustments based on concentration, Trio would eliminate the need for users to calculate conversions manually, enhancing convenience and safety.
	3.	Broader User Compatibility: Offering both U-100 and U-200 options could attract a wider range of users, accommodating those who prefer higher concentrations due to higher insulin needs or to minimize injection volumes.

This update could align with Trio’s commitment to personalized and advanced diabetes management, helping users manage insulin with greater ease and confidence.

**Comment by oddst** [comment]
I have a son using Lyumjev U-200 in Trio for the last 6 months or more. Doing this was challenging as many things has to be changed to do this successfully. Another challenge is that Lyumjev U-200 is "not" 200% of U-100, something the manufactorer also admits to on their webpages. Our experience is that Lyumjev U-200 is around 170% as powerful as U-100...! It should be allowed for differences between the insulin types available with U-200., both with regard to insulin brands and possibly also individual metabolism.

Secondly, this work could be started with enhancing the Trio documentation regarding the use of U-200 insulin. What settings should be changed, how much and why?

We have had to change the more obvious settings like:

- Basal
- Carb Ratio
- Insulin Sensitivity Factor

But we have also had to change the following as well:

- Max SMB Basal Minutes
- Max UAM SMB Basal Minutes
- Autosens Max
- Autosens Min

Other settings that might be needed to be looked at, depending on your usage:

- Recommended Bolus Percentage
- Max IOB
- Max COB
- Adjustment Factor
- Simoid Adjustment Factor
- Weighted Average of TDD
- SMB Delivery Ratio

and this makes the following settings even more important that they are correct:

- Insulin Curve
- Insulin DIA
- Insulin Peak Time

The current Bolus calculator in Trio is a Nightmare for us, as it does not take the CR settings into account at all. We are looking really forward to the new bolus calculator in Trio version 1.0.0...!!!

The upcoming Remote functionality in Trio and LoopFollow will also be affected by U-200, especially the Remote Bolus function where the user must remember that they ar using U-200 and manually calculate the needed Bolus (Trio provides info about needed Bolus, but multiplying that with 1.7x in your head is not always that easy - in our case). 

As there seems to be an increasing amount of users using U-200 insulin, supporting this directly in Trio would be very helpful for those users...! 

There might also be more loopers interested in using U-200 insulin, as:

- Insulin is delivered almost twice as fast as with U-100 insulin (since each Omnipod pulse is 0.05U of U-100 isnulin, but almost twice that with U-200 insulin)

- All Omnipods have a max bolus of 30U, and for people with considerable insulin resistancy it is not uncommon to have to use very aggressive CR settings. My son has a CR of between 0.8-1.0 g/U. Without U-200 insulin this limits meals that Trio can handle resonably efficient to 30g (boys between 15-25 years of age, can often eat 60g or 90g - which creates a number of challenges - especially since they typically do not like to have to handle their diabetes manually)...! Using U-200 insulin makes us able to automate handling of meals up to 60g of carbs, and potentially more using fat/protein entries...!

As insulin resistance is increasing dramatically in the population, and using GLP-1/GIP is not always recommended when kids are still developing - any help in this area would be very helpful and welcome...!

**Comment by WEBSALJR** [comment]
The claim that Lyumjev U-200 is only about 170% as potent as U-100 is not officially confirmed by Eli Lilly, but it’s a perception shared by some users based on personal experience. Lyumjev U-200 is designed to be twice as concentrated as Lyumjev U-100, meaning each unit in the U-200 version should deliver roughly the same glucose-lowering effect as in U-100, but in half the volume. However, differences in how the body absorbs and processes the U-200 concentration can lead to variability in perceived strength or effectiveness.

Here are the factors contributing to this perception include:
	1.	Absorption Rates: Higher concentration insulins can sometimes behave differently in terms of how quickly and consistently they’re absorbed.
	2.	Injection Volume: Lower injection volume with U-200 can change the speed or effectiveness of insulin action, sometimes leading users to feel that U-200 doesn’t match the expected 200% potency.
	3.	Individual Metabolism: Personal factors like skin absorption, metabolic rate, and insulin resistance can impact how strongly someone feels the effects of U-200 insulin compared to U-100.

Though Lyumjev U-200 is officially intended to have the same potency per unit as U-100, these practical differences have led some to conclude it may feel closer to around 170% as potent rather than a full 200%.

**Comment by hredder58** [comment]
I use Lyumjev u200 and just reduced my basal rates by about 30 percent, same for ISF and my CR.  If this updates does make it, I'm assuming I would have to redo all of that. TBH, I think people who are on u200 and also using an AID, would be knowledgeable enough for the right correction factors. Also, take into consideration that if someone ,who does not use anything but u100, selects u200 accidentally can really cause issues. Just a thought.

**Comment by WEBSALJR** [comment]
Thanks for your thoughts on this! I use Lyumjev U200 as well, and for my setup, I set both bolus and basal rates at 50% of the U100 settings, while keeping my carb ratio (CR) and insulin sensitivity factor (ISF) unchanged. I also find the warning window helpful, as it prompts confirmation before dosage selection.

**Comment by LiroyvH** [comment]
Please see issue #264. Maybe its easier to append findings and suggestions to that and keep it all in one central issue.

**Comment by Sjoerd-Bo3** [comment]
Please see https://github.com/nightscout/Trio/issues/264 for this. Closing this because duplicate. Please post the observatrions there.
